name = "AztecDiamonds"
uuid = "8762d9c5-fcab-4007-8fd1-c6de73397726"
authors = ["Simeon David Schaub <schaub@mit.edu> and contributors"]
version = "0.2.5"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"

[weakdeps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
MakieExtension = ["Makie", "GeometryBasics"]

[compat]
Adapt = "4"
Base64 = "1"
Colors = "0.12, 0.13"
GeometryBasics = "0.4, 0.5"
ImageIO = "0.6"
ImageShow = "0.3"
KernelAbstractions = "0.9"
Makie = "0.21"
OffsetArrays = "1"
Transducers = "0.4"
julia = "1.9"
